### ISSUE TITLE
A4_1_Graziella_Sundblad

### ISSUE THREAD

**Issue by GrazySE** [GrazySE/Pfi2#1]
Hej
Jag kunde inte flytta bransch A4_1_Graziella_Sundblad till master...Däremot lyckades jag lägga till A4_2_Graziella_Sundblad till master .

Hur gör jag då för att flytta A4_1_Graziella_Sundblad till master? Jag får "rejected: non-fast-forward" meddelande

**Comment by bonnene** [comment]
Hej, du behöver inte flytta dom för denna uppgiften, bara lägg det direkt till master och gör inte flera branches när du gör nästkommande uppgifter. :)

**Comment by GrazySE** [comment]
Tack! Jag kunde dock flytta dem ändå hehe
Men nu vet jag vad som gäller! Ha en trevlig helg!
